/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ticketgenerator;

/**
 *
 * @author admin-PC
 */

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    //  String billNo="";
    private Double totalAmount=0.0;
    private Double cash=0.0;
    private Double balance=0.0;
    private Double bHeight=0.0;
    private Double listIVA;
    private Double subTotal=0.0;
    private Double CloseBox=0.0;
    private int ticketnumber=0;
    
    private ArrayList<String> itemName = new ArrayList<>();
    private ArrayList<String> quantity = new ArrayList<>();
    private ArrayList<String> itemPrice = new ArrayList<>();
    private ArrayList<String> subtotal = new ArrayList<>();
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtitemname = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttotalAmount = new javax.swing.JTextField();
        txtcash = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtticketnumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtclosebox = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Ticket");

        jLabel2.setText("Servicio");

        jLabel3.setText("Cantidad");

        jLabel5.setText("Precio con IVA");

        txtquantity.setText("1");

        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad a pagar");

        jLabel7.setText("Pago Efectivo");

        txttotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalAmountActionPerformed(evt);
            }
        });

        txtcash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcashMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 113, 92));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("Agregar Servicio");

        jLabel8.setText("Vuelta");

        txtbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalanceActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("Pago ");

        jButton4.setBackground(new java.awt.Color(133, 73, 73));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("New ticket");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtticketnumber.setText("0");

        jLabel4.setText("Numero de Ticket");

        jButton3.setBackground(new java.awt.Color(126, 126, 163));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cerrar Caja");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77" }));
        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Codigo Servicio");

        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 102));
        jButton6.setText("Aceptar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtitemname, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtticketnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtclosebox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(26, 26, 26)
                                        .addComponent(txttotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtcash, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclosebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtcash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtticketnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtitemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel8)
                                                .addGap(3, 3, 3))
                                            .addComponent(txtbalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        itemName.add(txtitemname.getText());
        quantity.add(txtquantity.getText());
        subtotal.add(txtsubtotal.getText());
        totalAmount = totalAmount + (Double.valueOf(txtsubtotal.getText())*Double.valueOf(txtquantity.getText()));
        txttotalAmount.setText(totalAmount + "");
        subTotal = Double.valueOf(txtsubtotal.getText());
        listIVA();
        clear();   
    }//GEN-LAST:event_jButton1ActionPerformed
    private void closebox()
    {
        CloseBox = CloseBox+totalAmount;
        System.out.println(CloseBox);
    }
    private void cleanALL()
    {
        ticketnumber=0;
        txtticketnumber.setText("0");
        txtitemname.setText("");
        txtquantity.setText("1");
        txtsubtotal.setText("");
        txttotalAmount.setText("");
        txtcash.setText("");
        txtbalance.setText("");
        itemName.clear();
        quantity.clear();
        itemPrice.clear();
        subtotal.clear();
    }
    private void ticketNumber()
    {
        txtticketnumber.setText(ticketnumber+"");
    }
    
    private void listIVA()
    {
        listIVA = subTotal*(0.79);
        listIVA=Math.round(listIVA*100.0)/100.0;
        itemPrice.add(""+listIVA);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        bHeight = Double.valueOf(itemName.size());
        //JOptionPane.showMessageDialog(rootPane, bHeight);
        
        PrinterJob pj = PrinterJob.getPrinterJob();        
        pj.setPrintable(new BillPrintable(),getPageFormat(pj));
        try {
             pj.print();
          
        }
         catch (PrinterException ex) {
                 ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        closebox();
        newTicket();
        ticketNumber();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        closebox();
        txtclosebox.setText(CloseBox+"");
        cleanALL();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
        // TODO add your handling code here:
        String servicio=(String)combo1.getSelectedItem();
        if(servicio.equals("1"))
        {
            txtsubtotal.setText("14.00");
            txtitemname.setText("Corte Dama") ; 
        }
        if(servicio.equals("2"))
        {
            txtsubtotal.setText("13.00");
            txtitemname.setText("Corte Caballero") ; 
        }
         if(servicio.equals("3"))
        {
            txtsubtotal.setText("27.00");
            txtitemname.setText("Tinte") ; 
        }
        if(servicio.equals("4"))
        {
            txtsubtotal.setText("35.00");
            txtitemname.setText("Mechas") ; 
        }
         if(servicio.equals("5"))
        {
            txtsubtotal.setText("7.00");
            txtitemname.setText("Lavado") ; 
        }
        if(servicio.equals("6"))
        {
            txtsubtotal.setText("29.50");
            txtitemname.setText("Peinar + Cortar") ; 
        }
         if(servicio.equals("7"))
        {
            txtsubtotal.setText("11.50");
            txtitemname.setText("Lavado Pelo Largo") ; 
        }
        if(servicio.equals("8"))
        {
            txtsubtotal.setText("14.50");
            txtitemname.setText("Peinar Pelo Corto") ; 
        }
         if(servicio.equals("9"))
        {
            txtsubtotal.setText("16.50");
            txtitemname.setText("Peinar Pelo Medio") ; 
        }
        if(servicio.equals("10"))
        {
            txtsubtotal.setText("18.50");
            txtitemname.setText("Peinar Pelo Largo") ; 
        }
        
        if(servicio.equals("11"))
        {
            txtsubtotal.setText("25.50");
            txtitemname.setText("Peinar Pelo Extra Largo") ; 
        }
        if(servicio.equals("12"))
        {
            txtsubtotal.setText("39.50");
            txtitemname.setText("Peinar + Tinte") ; 
        }
         if(servicio.equals("13"))
        {
            txtsubtotal.setText("52.50");
            txtitemname.setText("Peinar + Corte + Tinte") ; 
        }
        if(servicio.equals("14"))
        {
            txtsubtotal.setText("49.50");
            txtitemname.setText("Peinar + Mechas") ; 
        }
         if(servicio.equals("15"))
        {
            txtsubtotal.setText("63.50");
            txtitemname.setText("Peinar + Corte + Mechas") ; 
        }
        if(servicio.equals("16"))
        {
            txtsubtotal.setText("78.50");
            txtitemname.setText("Peinar + Tinte + Mechas") ; 
        }
         if(servicio.equals("17"))
        {
            txtsubtotal.setText("83.50");
            txtitemname.setText("Peinar + Corte + Tinte + Mechas") ; 
        }
        if(servicio.equals("18"))
        {
            txtsubtotal.setText("68.50");
            txtitemname.setText("Corte + Tinte + Mechas") ; 
        }
         if(servicio.equals("19"))
        {
            txtsubtotal.setText("49.00");
            txtitemname.setText("Corte + Mechas") ; 
        }
        if(servicio.equals("20"))
        {
            txtsubtotal.setText("62.00");
            txtitemname.setText("Tinte + Mechas") ; 
        }
        
        if(servicio.equals("21"))
        {
            txtsubtotal.setText("54.50");
            txtitemname.setText("Peinar + Barros") ; 
        }
        if(servicio.equals("22"))
        {
            txtsubtotal.setText("64.50");
            txtitemname.setText("Peinar + Cortar + Barros") ; 
        }
         if(servicio.equals("23"))
        {
            txtsubtotal.setText("44.50");
            txtitemname.setText("Cortar + Barros") ; 
        }
        if(servicio.equals("24"))
        {
            txtsubtotal.setText("30.00");
            txtitemname.setText("Barros") ; 
        }
         if(servicio.equals("25"))
        {
            txtsubtotal.setText("0.50");
            txtitemname.setText("Suplemento") ; 
        }
        if(servicio.equals("26"))
        {
            txtsubtotal.setText("4.00");
            txtitemname.setText("Mascarilla") ; 
        }
         if(servicio.equals("27"))
        {
            txtsubtotal.setText("39.00");
            txtitemname.setText("Corte + Tinte") ; 
        }
        if(servicio.equals("28"))
        {
            txtsubtotal.setText("1.00");
            txtitemname.setText("Serum") ; 
        }
         if(servicio.equals("29"))
        {
            txtsubtotal.setText("1.00");
            txtitemname.setText("Champú Normal") ; 
        }
        if(servicio.equals("30"))
        {
            txtsubtotal.setText("2.00");
            txtitemname.setText("Champú Especial") ; 
        }
        
        if(servicio.equals("31"))
        {
            txtsubtotal.setText("3.00");
            txtitemname.setText("crema") ; 
        }
        if(servicio.equals("32"))
        {
            txtsubtotal.setText("13.00");
            txtitemname.setText("Arreglo Barba") ; 
        }
         if(servicio.equals("33"))
        {
            txtsubtotal.setText("15.00");
            txtitemname.setText("Afeitado") ; 
        }
         if(servicio.equals("34"))
        {
            txtsubtotal.setText("7.00");
            txtitemname.setText("Solo Maquina") ; 
        }
         if(servicio.equals("35"))
        {
            txtsubtotal.setText("50.00");
            txtitemname.setText("Recogido") ; 
        }
         if(servicio.equals("36"))
        {
            txtsubtotal.setText("20.00");
            txtitemname.setText("Semirecogido") ; 
        }
        if(servicio.equals("37"))
        {
            txtsubtotal.setText("50.00");
            txtitemname.setText("Bono Rayos") ; 
        }
         if(servicio.equals("38"))
        {
            txtsubtotal.setText("150.00");
            txtitemname.setText("Ácido") ; 
        }
        if(servicio.equals("39"))
        {
            txtsubtotal.setText("68.50");
            txtitemname.setText("Botox") ; 
        }
         if(servicio.equals("40"))
        {
            txtsubtotal.setText("8.50");
            txtitemname.setText("Champú de Fanola") ; 
        }
        if(servicio.equals("41"))
        {
            txtsubtotal.setText("30.00");
            txtitemname.setText("Moldeador") ; 
        }
        
        if(servicio.equals("42"))
        {
            txtsubtotal.setText("80.00");
            txtitemname.setText("Botox Capilar") ; 
        }
        if(servicio.equals("43"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Suplemento Pelo Largo") ; 
        }
         if(servicio.equals("44"))
        {
            txtsubtotal.setText("35.00");
            txtitemname.setText("Mechas Parciales con Matiz") ; 
        }
        if(servicio.equals("45"))
        {
            txtsubtotal.setText("40.00");
            txtitemname.setText("Decoloración") ; 
        }
         if(servicio.equals("46"))
        {
            txtsubtotal.setText("45.00");
            txtitemname.setText("Mechas Californianas") ; 
        }
        if(servicio.equals("47"))
        {
            txtsubtotal.setText("45.00");
            txtitemname.setText("Mechas Baby Light") ; 
        }
         if(servicio.equals("48"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Suplemento Pelo Extra Largo") ; 
        }
        if(servicio.equals("49"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Suplemento Mechas Bicolor") ; 
        }
        
        if(servicio.equals("50"))
        {
            txtsubtotal.setText("5.00");
            txtitemname.setText("Suplemento de Tinte") ; 
        }
        if(servicio.equals("51"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Suplemento Matiz Pelo Largo") ; 
        }      
        if(servicio.equals("52"))
        {
            txtsubtotal.setText("15.00");
            txtitemname.setText("Suplemento Matiz Pelo Extra Largo") ; 
        }
        if(servicio.equals("53"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Suplemento Champú Vitalizante") ; 
        }
         if(servicio.equals("54"))
        {
            txtsubtotal.setText("17.00");
            txtitemname.setText("Hidratación") ; 
        }
        if(servicio.equals("55"))
        {
            txtsubtotal.setText("12.00");
            txtitemname.setText("Piernas Completas Mujer") ; 
        }
         if(servicio.equals("56"))
        {
            txtsubtotal.setText("18.00");
            txtitemname.setText("Piernas Completas Hombre") ; 
        }
        if(servicio.equals("57"))
        {
            txtsubtotal.setText("9.00");
            txtitemname.setText("Medias Piernas Mujer") ; 
        }
        if(servicio.equals("58"))
        {
            txtsubtotal.setText("14.00");
            txtitemname.setText("Medias Piernas Hombre") ; 
        }
        if(servicio.equals("59"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Muslo Mujer") ; 
        }
        if(servicio.equals("60"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Brazos Mujer") ; 
        }
        if(servicio.equals("61"))
        {
            txtsubtotal.setText("16.00");
            txtitemname.setText("Brazos Hombre") ; 
        }
        
         if(servicio.equals("62"))
        {
            txtsubtotal.setText("7.00");
            txtitemname.setText("Medios Brazos Mujer") ; 
        }
        if(servicio.equals("63"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Medios Brazos Hombre") ; 
        }
         if(servicio.equals("64"))
        {
            txtsubtotal.setText("15.00");
            txtitemname.setText("Pecho Mujer") ; 
        }
        if(servicio.equals("65"))
        {
            txtsubtotal.setText("17.00");
            txtitemname.setText("Pecho Hombre") ; 
        }
         if(servicio.equals("66"))
        {
            txtsubtotal.setText("14.00");
            txtitemname.setText("Espalda Mujer") ; 
        }
        if(servicio.equals("67"))
        {
            txtsubtotal.setText("18.00");
            txtitemname.setText("Espalda Hombre") ; 
        }
        if(servicio.equals("68"))
        {
            txtsubtotal.setText("9.00");
            txtitemname.setText("Ingles Normales Mujer") ; 
        }
        if(servicio.equals("69"))
        {
            txtsubtotal.setText("15.00");
            txtitemname.setText("Ingles Brasileñas Mujer") ; 
        }
        if(servicio.equals("70"))
        {
            txtsubtotal.setText("32.00");
            txtitemname.setText("Ingles Brasileñas Hombre") ; 
        }
        if(servicio.equals("71"))
        {
            txtsubtotal.setText("22.00");
            txtitemname.setText("Ingles Completas Mujer") ; 
        }
        
         if(servicio.equals("72"))
        {
            txtsubtotal.setText("6.00");
            txtitemname.setText("Axilas Mujer") ; 
        }
        if(servicio.equals("73"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Axilas Hombre") ; 
        }
         if(servicio.equals("74"))
        {
            txtsubtotal.setText("7.00");
            txtitemname.setText("Lumbares Mujer") ; 
        }
        if(servicio.equals("75"))
        {
            txtsubtotal.setText("10.00");
            txtitemname.setText("Lumbares Hombre") ; 
        }
         if(servicio.equals("76"))
        {
            txtsubtotal.setText("3.00");
            txtitemname.setText("Lavio mujer") ; 
        }
        if(servicio.equals("77"))
        {
            txtsubtotal.setText("6.00");
            txtitemname.setText("Cejas Hombre o Mujer") ; 
           }  
    }//GEN-LAST:event_combo1ItemStateChanged

    private void txttotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalAmountActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalanceActionPerformed
        // TODO add your handling code here:
               
    }//GEN-LAST:event_txtbalanceActionPerformed

    private void txtcashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcashMouseClicked

    }//GEN-LAST:event_txtcashMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        if (Double.valueOf(txtcash.getText()) > 0){
                    balance=0.0;
                    balance = (totalAmount - Double.valueOf(txtcash.getText()))*(-1);
                    txtbalance.setText(balance + "");
               }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed
    
    private void newTicket(){
        txttotalAmount.setText("");
        txtcash.setText("");
        txtbalance.setText("");
        ticketnumber++;
        totalAmount=0.0;
        balance=0.0;
        itemName.clear();
        quantity.clear();
        itemPrice.clear();
        subtotal.clear();
        
    }
    
    private void clear()
    {
        txtitemname.setText("");
        txtquantity.setText("1");
        txtsubtotal.setText("");
    }
    
//Aqui indicamos las dimensiones del papel
    
    public PageFormat getPageFormat(PrinterJob pj)
{
    
    PageFormat pf = pj.defaultPage();
    Paper paper = pf.getPaper();    

    double bodyHeight = bHeight;  
    double headerHeight = 5.0;                  
    double footerHeight = 5.0;        
    double width = cm_to_pp(8); 
    double height = cm_to_pp(headerHeight+bodyHeight+footerHeight); 
    paper.setSize(width, height);
    paper.setImageableArea(0,10,width,height - cm_to_pp(1));  
            
    pf.setOrientation(PageFormat.PORTRAIT);  
    pf.setPaper(paper);    

    return pf;
}
    
    protected static double cm_to_pp(double cm)
    {            
	        return toPPI(cm * 0.393600787);            
    }
 
    protected static double toPPI(double inch)
    {            
	        return inch * 72d;            
    }
    
  public class BillPrintable implements Printable {
     
  public int print(Graphics graphics, PageFormat pageFormat,int pageIndex) 
  throws PrinterException 
  {    
      
      int r= itemName.size();
      ImageIcon icon=new ImageIcon("C:\\PARABEUS.jpg"); 
      int result = NO_SUCH_PAGE;    
        if (pageIndex == 0) {                    
        
            Graphics2D g2d = (Graphics2D) graphics;                    
            double width = pageFormat.getImageableWidth();                               
            g2d.translate((int) pageFormat.getImageableX(),(int) pageFormat.getImageableY()); 



          //  FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));
     
        try{
            int y=20;
            int yShift = 10;
            int headerRectHeight=15;
           // int headerRectHeighta=40;
            
                
            g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
            g2d.drawImage(icon.getImage(), 50, 20, 90, 30, rootPane);y+=yShift+30;
            g2d.drawString("-------------------------------------",10,y);y+=yShift;
            g2d.drawString("         Parabeus S.L        ",10,y);y+=yShift;
            g2d.drawString("       Ticket number "+ticketnumber,10,y);y+=yShift;
            g2d.drawString("       Calle Sagasta n 15    ",10,y);y+=yShift;
            g2d.drawString("       +34 915 21 48 86      ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------",10,y);y+=headerRectHeight;

            g2d.drawString(" Item Name                  Price   ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------",10,y);y+=headerRectHeight;
     
            for(int s=0; s<r; s++)
            {
                
            g2d.drawString(" "+itemName.get(s)+"                            ",10,y);y+=yShift;
            g2d.drawString("      "+quantity.get(s)+" * "+itemPrice.get(s),10,y); g2d.drawString(subtotal.get(s),160,y);y+=yShift;

            }
          
            g2d.drawString("-------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Total amount:               "+txttotalAmount.getText()+"   ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Cash      :                 "+txtcash.getText()+"   ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Balance   :                 "+balance+"   ",10,y);y+=yShift;
  
            g2d.drawString("*************************************",10,y);y+=yShift;
            g2d.drawString("       THANK YOU COME AGAIN          ",10,y);y+=yShift;
            g2d.drawString("*************************************",10,y);y+=yShift;
            g2d.drawString("       SOFTWARE BY:PARABEUS          ",10,y);y+=yShift;
            g2d.drawString("CONTACT: parabeuspeluqueria@gmail.com",10,y);y+=yShift;  
           

    }
    catch(Exception e){
    e.printStackTrace();
    }

              result = PAGE_EXISTS;    
          }    
          return result;    
      }
   }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtclosebox;
    private javax.swing.JTextField txtitemname;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txtticketnumber;
    private javax.swing.JTextField txttotalAmount;
    // End of variables declaration//GEN-END:variables
}
